version: 2.1
jobs:
  build-frontend:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: "Build front-end"
          command:  |
            cd frontend
            npm install
            npm update 
            npm run build
          
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build


  build-backend:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: "Build back-end"
          command:  |
            cd backend
            npm install
            npm update
            npm audit
            npm run build
          
          
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
  
  


workflows:
  say-false:
    jobs:
      - build-frontend
      - build-backend


    